# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Lightddns
site_url: https://lightddns.duaky.com
site_author: duakc
repo_url: https://github.com/duakc/lightddns
repo_name: duakc/lightddns
copyright: Copyright &copy; 2026 duakc
site_description: Lightweight DDNS(Dynamic DNS) Prog.
remote_branch: ci/docs
edit_uri: ""
nav:
  - Home: index.md
  - Manual:
      - Overview: manual/index.md
      - Cloudflare: manual/cloudflare.md
      - Aliyun: manual/aliyun.md
      - TencentCloud: manual/tencentcloud.md
      - Groups: manual/groups.md
      - Services: manual/services.md
  - Configuration:
      - Options: configuration/options.md
      - Log: configuration/log.md
      - Domain: configuration/domain.md
      - Datasources:
          - HTTP: configuration/datasource/http.md
          - Netlink: configuration/datasource/netlink.md
          - Command: configuration/datasource/command.md
          - Sum: configuration/datasource/sum.md
          - Failover: configuration/datasource/failover.md
      - Providers:
          - Cloudflare: configuration/provider/cloudflare.md
          - Aliyun: configuration/provider/aliyun.md
          - TencentCloud: configuration/provider/tencentcloud.md
      - Services:
          - Prometheus: configuration/service/prometheus.md
          - IPServer: configuration/service/ipserver.md
      - Shared:
          - ConnectOption: configuration/shared/connect.md
          - HTTPOption: configuration/shared/http.md
          - DNSOption: configuration/shared/dns.md
theme:
  name: material
  features:
#   mkdocs_static_i18n:
#   mkdocs-material language switcher contextual link is not compatible with
#   theme.features = navigation.instant
#    - navigation.instant
#    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.prune
    - search.suggest
    - search.highlight
  font:
    text: Roboto
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to system preference
plugins:
  - privacy
  - search:
      lang: en
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      fallback_to_default: true
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: zh
          name: 简体中文
          build: true
          default: false
          nav_translations:
            Home: Home
            Manual: 手册
            Overview: 总览
            Cloudflare: Cloudflare
            Aliyun: 阿里云
            TencentCloud: 腾讯云
            Groups: 分组数据源
            Configuration: 配置
            Options: 配置文件
            Log: 日志
            Domain: 域名
            Datasources: 数据源
            HTTP: HTTP
            Netlink: Netlink
            Command: Command
            Sum: Sum
            Failover: Failover
            Providers: 服务提供方
            Services: 服务
            Prometheus: Prometheus
            IPServer: IPServer
            Shared: 共享
            ConnectOption: ConnectOption
            HTTPOption: HTTPOption
            DNSOption: DNSOption
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption