// Code generated by gen_serializers.go; DO NOT EDIT.

package ipserver

import (
	"github.com/duakc/mt/freebuf"
)

func (resp *Response) writeYAML(buf freebuf.Buffer) int {
	buf.Grow(23 + len(resp.IP)) // exact: constants + len(strings) + worst-case bool
	n := 0
	buf.WriteString(`ip: `)
	n += 4
	buf.WriteByte('"')
	n++
	buf.WriteString(resp.IP)
	n += len(resp.IP)
	buf.WriteByte('"')
	n++
	buf.WriteByte('\n')
	n++
	buf.WriteString(`is_bogon: `)
	n += 10
	if resp.IsBogon {
		buf.WriteString("true")
		n += 4
	} else {
		buf.WriteString("false")
		n += 5
	}
	buf.WriteByte('\n')
	n++
	return n
}
