// Code generated by gen_serializers.go; DO NOT EDIT.

package ipserver

import (
	"bytes"
)

func (resp Response) writeYAML(buffer *bytes.Buffer) {
	buffer.Grow(76) // estimated size: keys + avg value cost
	buffer.WriteString(`ip: `)
	buffer.WriteByte('"')
	buffer.WriteString(resp.IP)
	buffer.WriteByte('"')
	buffer.WriteByte('\n')
	buffer.WriteString(`is_bogon: `)
	if resp.IsBogon {
		buffer.WriteString("true")
	} else {
		buffer.WriteString("false")
	}
	buffer.WriteByte('\n')
	buffer.WriteString(`time: `)
	buffer.WriteByte('"')
	buffer.WriteString(resp.Time)
	buffer.WriteByte('"')
	buffer.WriteByte('\n')
}
