// Code generated by gen_serializers.go; DO NOT EDIT.

package ipserver

import (
	"github.com/duakc/mt/freebuf"
)

func (resp *Response) writeJSON(buf freebuf.Buffer) int {
	buf.Grow(26 + len(resp.IP)) // exact: constants + len(strings) + worst-case bool
	n := 0
	buf.WriteByte('{')
	n++
	buf.WriteString(`"ip":`)
	n += 5
	buf.WriteByte('"')
	n++
	buf.WriteString(resp.IP)
	n += len(resp.IP)
	buf.WriteByte('"')
	n++
	buf.WriteByte(',')
	n++
	buf.WriteString(`"is_bogon":`)
	n += 11
	if resp.IsBogon {
		buf.WriteString("true")
		n += 4
	} else {
		buf.WriteString("false")
		n += 5
	}
	buf.WriteByte('}')
	n++
	return n
}
