// Code generated by gen_serializers.go; DO NOT EDIT.

package ipserver

import (
	"bytes"
)

func (resp Response) writeJSON(buffer *bytes.Buffer) {
	buffer.Grow(80) // estimated size: keys + avg value cost
	buffer.WriteByte('{')
	buffer.WriteString(`"ip":`)
	buffer.WriteByte('"')
	buffer.WriteString(resp.IP)
	buffer.WriteByte('"')
	buffer.WriteByte(',')
	buffer.WriteString(`"is_bogon":`)
	if resp.IsBogon {
		buffer.WriteString("true")
	} else {
		buffer.WriteString("false")
	}
	buffer.WriteByte(',')
	buffer.WriteString(`"time":`)
	buffer.WriteByte('"')
	buffer.WriteString(resp.Time)
	buffer.WriteByte('"')
	buffer.WriteByte('}')
}
