workingDir: "./cmd/lightddns/"
outputDir: "build/bin"
binaryName: "lightddns"
qualified: true
buildName: ""
tags:
  # uncomment below to enable some tags
  # - "freebuf_low_mem"
  # - "debug"
env:
  # CGO_ENABLED: "0"